[package]
name = "py-konclude"
description = "A wrapper around konclude"
version = "0.1.0"
authors = ["Björn Gehrke <bjoern.gehrke+pykonclude@uzh.ch>"]
edition = "2024"

[lib]
name="pykonclude"
crate-type=["cdylib"]

[dependencies]
horned-owl = "^1.4"
konclude-rs = { path = "../konclude-rs" }
py-horned-owl-reasoner = { git = "https://github.com/ontology-tools/py-horned-owl" }
